#%RAML 0.8
title: CcsProfuturo 
version: 18.2.3
baseUri: /mobile/custom/CcsProfuturo
protocols: [HTTPS]
/components:
  description: |
    Components context root
    
  get:
    displayName: Metadata
    description: |
      Components metadata retrieval
      
    protocols: [HTTPS]
    responses:
      200:
        body:
          application/json:
            example: |
              [
                {
                  "name": "say_hello",
                  "properties": {
                    "name": { "type": "string", "required": true }
                  },
                  "supportedActions": [
                  ]
                }
              ]
              
  /{componentName}:
    description: |
      Component invocation
      
    uriParameters:
      componentName:
        displayName: componentName
        description: |
          Name of the component
          
        type: string
        required: true
    post:
      description: |
        Invoke the named component
        
      body:
        application/json:
      responses:
        200:
          body:
            application/json: